### ISSUE TITLE
希望能支持保存图片

### ISSUE THREAD

**Issue by perfumescent** [Marverlises/ChatGPT-To-Markdown-google-plugin#1]
![image](https://github.com/thisisbaiy/ChatGPT-To-Markdown-google-plugin/assets/31856209/d17168f7-1c5d-41e8-89af-27eb3ebebdff)
 直接点击导出时，图片不会下载。

**Comment by Marverlises** [comment]
在写的时候暂时没有支持GPT-4，现在我改一下，目前已经发布了插件，可以直接下载插件，我后续会更新，这是插件地址：https://chromewebstore.google.com/detail/chatgpt-to-markdown-plus/gcocgmkjaagjcijfmocbjghbpinamnhp

**Comment by Marverlises** [comment]
此处代码已更新可支持导出图片功能，现在会更新插件

**Comment by perfumescent** [comment]
牛的！

**Comment by Marverlises** [comment]
😀
