### ISSUE TITLE
发个Issues鼓励一下作者，非常棒的扩展

### ISSUE THREAD

**Issue by XiaoBaiXBS** [Marverlises/ChatGPT-To-Markdown-google-plugin#2]
发个Issues鼓励一下作者，非常棒的扩展

**Comment by Marverlises** [comment]
哈哈感谢认可，这个目前已经在google插件市场发布了，可以直接用插件更方便一些，这是link：[ChatGPT to MarkDown plus
](https://chromewebstore.google.com/detail/chatgpt-to-markdown-plus/gcocgmkjaagjcijfmocbjghbpinamnhp?hl=zh-CN&utm_source=ext_sidebar)
